prometheus:
  # prometheusSpec 내부가 아니라, prometheus 바로 아래에 service가 와야 합니다.
  service:
    type: NodePort
    nodePort: 30001

  prometheusSpec:
    # 프로메테우스 인스턴스 자체에 대한 설정(이미지, 리소스 등)은 여기에 들어갑니다.
    nodeExporter:
      enabled: true

grafana:
  service:
    type: NodePort
    nodePort: 30002

nodeExporter:
  enabled: true

alertmanager:
  enabled: false
